### ISSUE TITLE
Put this package on Pypi?

### ISSUE THREAD

**Issue by utf** [WMD-group/kgrid#7]
I love kgrid and I use it all the time. I want to use its functionality in a package I'm developing and sure, I could copy the source and use it directly, but it would be nice if kgrid was on Pypi.

Thoughts?

**Comment by ajjackson** [comment]
Good idea :-)

**Comment by ajjackson** [comment]
Done! https://pypi.org/project/kgrid/

Did a quick test in an Ubuntu docker instance and it seems to work
